project:
  type: website
  output-dir: _site
  render:
   # - index.qmd                  # (если есть)
    - other/intro-presentation.qmd

website:
  title: "mgimo-foreign-trade"
  navbar:
    left:
      - text: "Вводная презентация"
        href: other/intro-presentation.qmd

format:
  html:
    theme: cosmo
