name: Quarto Publish

on:
  push:
    branches: [ main ]
    paths:
      - "other/**.qmd"
      - "_quarto.yml"
      - ".github/workflows/publish.yml"
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # нужно для пуша в gh-pages

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Quarto (pin version)
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "1.7.34"   # latest - не работает почему-то

      - name: Show Quarto version (debug)
        run: quarto --version

      # Рендерим весь проект (но что именно рендерить — лучше указать в _quarto.yml -> project.render)
      - name: Render site
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: "."

      # Публикуем содержимое _site в ветку gh-pages (Pages уже настроен на эту ветку)
      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: _site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
