name: Quarto Publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Quarto (pin version)
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # укажите конкретную версию, которая есть в Releases:
          version: "1.7.34"

      - name: Show Quarto version (debug)
        run: quarto --version

      # Если в .qmd есть код на Python/R — раскомментируйте нужные блоки
      # - name: Setup Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.12'
      # - name: Install Python deps
      #   run: pip install -r requirements.txt
      # - name: Setup R
      #   uses: r-lib/actions/setup-r@v2

      - name: Render site
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: "."

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: _site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
